---
- name: Install apache2
  apt:
    name: apache2
    state: present
    update_cache: yes
  become: yes
  notify: Restart apache service

- name: Enable apache module proxy proxy_http proxy_balancer
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http
    - proxy_balancer
    - rewrite
  become: yes
  notify: Restart apache service